In [2]:
import pandas as pd
import numpy  as np
Path = "C:\\Users\\86187\\Desktop\\"
path1="smart_dataset_sample.csv"
px_all =pd.read_csv(Path+path1)

#px_all = px_all.dropna(how ='all',axis = 1)#剔除全部缺失的列
px_all = px_all.fillna(px_all.mean()) #对于部分缺失的列使用均值填充缺失值
px_all = px_all.drop(['serial_number'],axis=1)
print(px_all)


       Unnamed: 0  capacity_bytes  failure  smart_5_raw  smart_187_raw  \
0             157    4.000790e+12        0          0.0            0.0   
1           21511    4.000790e+12        0          0.0            0.0   
2            1967    4.000790e+12        0          0.0            0.0   
3            7488    4.000790e+12        1          0.0           16.0   
4            9598    4.000790e+12        1       1856.0           32.0   
...           ...             ...      ...          ...            ...   
11031       24249    4.000790e+12        1          0.0            4.0   
11032        2002    4.000790e+12        0          0.0            0.0   
11033       23970    4.000790e+12        0          0.0            0.0   
11034        4797    4.000790e+12        1          0.0            0.0   
11035       22252    4.000790e+12        1        160.0           12.0   

       smart_188_raw  smart_197_raw  smart_198_raw  smart_9_raw  \
0                0.0            0.0         

In [3]:
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing   import normalize
m_px_all = np.array(px_all.values)
train_target = m_px_all[:,2]
train_data  = np.delete(m_px_all,2,1)#除了[2]列之外的所有列都是训练属性

train_data = normalize(train_data,axis=0,norm='max')
print(train_data)
x_train,x_test, y_train, y_test = train_test_split(train_data,train_target,test_size=0.3, random_state=0)

svc = svm.SVC(C=0.8,kernel = 'rbf',gamma=20, decision_function_shape='ovr')
svc.fit(x_train,y_train)

svc.score(x_test,y_test)

[[0.00493013 1.         0.         ... 0.14184397 0.6835003  0.28174458]
 [0.67549066 1.         0.         ... 0.17021277 0.41067242 0.57740624]
 [0.06176794 1.         0.         ... 0.14893617 0.84920553 0.22004731]
 ...
 [0.75270843 1.         0.         ... 0.14184397 0.41367768 0.51536235]
 [0.15063589 1.         0.         ... 0.15602837 0.53124328 0.78141057]
 [0.69875962 1.         0.00366905 ... 0.17021277 0.51437291 0.40867669]]


0.6381757777106615